#ifndef __MBEDTLS_DEVICE_H__
#define __MBEDTLS_DEVICE_H__

#define MBEDTLS_AES_SETKEY_ENC_ALT
#define MBEDTLS_AES_SETKEY_DEC_ALT
#define MBEDTLS_AES_ENCRYPT_ALT
#define MBEDTLS_AES_DECRYPT_ALT

#endif
